# Generated by Django 3.1.1 on 2021-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bienpat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coddep', models.CharField(max_length=30)),
                ('codamb', models.CharField(max_length=10)),
                ('codeti', models.CharField(max_length=30)),
                ('descbien', models.CharField(max_length=30)),
                ('serbien', models.CharField(max_length=50)),
                ('modbien', models.DateField(null=True)),
                ('marbien', models.CharField(max_length=15)),
                ('dniper', models.CharField(max_length=5)),
                ('valbien', models.IntegerField()),
                ('estbien', models.CharField(max_length=5)),
            ],
        ),
    ]
