# Generated by Django 3.1.1 on 2021-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpat',
            name='codamb',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='coddep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='codeti',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='descbien',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='dniper',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='estbien',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='bienpat',
            name='modbien',
            field=models.CharField(max_length=15),
        ),
    ]
