# Generated by Django 3.1.1 on 2021-07-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0002_auto_20210708_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienpat',
            old_name='codamb',
            new_name='codAmb',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='coddep',
            new_name='codDep',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='codeti',
            new_name='codEti',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='dniper',
            new_name='codPlaper',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='descbien',
            new_name='desBien',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='estbien',
            new_name='estBien',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='marbien',
            new_name='marBien',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='modbien',
            new_name='modBien',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='serbien',
            new_name='serBien',
        ),
        migrations.RenameField(
            model_name='bienpat',
            old_name='valbien',
            new_name='valBien',
        ),
    ]
