# Generated by Django 3.1.1 on 2021-07-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0003_auto_20210708_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienpat',
            old_name='codPlaper',
            new_name='codPlaPer',
        ),
    ]
