# Generated by Django 3.1.1 on 2021-07-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0004_auto_20210708_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDep', models.CharField(max_length=8)),
                ('descDep', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bienpat',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cip.dependencia'),
            preserve_default=False,
        ),
    ]
