# Generated by Django 3.1.1 on 2021-07-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0006_auto_20210712_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienpat',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cip.dependencia'),
            preserve_default=False,
        ),
    ]
