# Generated by Django 3.1.1 on 2021-07-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0007_auto_20210713_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dniPer', models.CharField(max_length=8)),
                ('apePatPer', models.CharField(max_length=50)),
                ('apeMatPer', models.CharField(max_length=50)),
                ('nomPer', models.CharField(max_length=50)),
                ('codPlaPer', models.CharField(max_length=50)),
                ('fecNacPer', models.DateField(null=True)),
                ('estPer', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='bienpat',
            name='codPlaPer',
        ),
        migrations.AddField(
            model_name='bienpat',
            name='situBien',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AddField(
            model_name='bienpat',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cip.personal'),
            preserve_default=False,
        ),
    ]
