# Generated by Django 3.1.1 on 2021-07-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0008_auto_20210715_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='bienImag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cip.bienpat')),
            ],
        ),
    ]
