# Generated by Django 3.1.1 on 2021-08-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0009_bienimag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienpat',
            name='personal',
        ),
        migrations.CreateModel(
            name='bienPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cip.bienpat')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cip.personal')),
            ],
        ),
    ]
