# Generated by Django 3.1.1 on 2021-08-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0011_auto_20210801_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpat',
            name='codEti',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='codDep',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dniPer',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
