# Generated by Django 3.1.1 on 2021-09-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0013_auto_20210801_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='certiDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecOtor', models.DateField()),
                ('fecLimInsta', models.DateField()),
                ('fecInsta', models.DateField()),
                ('fecVenci', models.DateField()),
                ('obsCerti', models.CharField(max_length=50)),
                ('tipoCerti', models.CharField(max_length=30)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cip.personal')),
            ],
        ),
    ]
